import { describe, it, expect, vi, beforeEach } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { FeedbackKit } from '../src';
import type { Comment } from '../src/models/types';

/**
 * `QA-UNIT04-COMMENTS` `-11`, JS half — the JS SDK decodes the payload the server
 * actually sends onto the `Comment` interface's exact field set.
 *
 * The corpus is **not** written here. It is generated by the server target's
 * `CommentWireContractTests` from the server's own `CommentResponseDTO` through the
 * server's own configured encoder, and that suite byte-diffs this committed copy against
 * a fresh regeneration. A hand-written literal here would be a fifth independent guess at
 * one wire contract.
 *
 * The transform under test is `HttpClient`'s recursive `snakeToCamel`, which is module-
 * private. Rather than re-implement it (a second definition, and the exact thing this
 * suite exists to prevent), the case drives the **real** `FeedbackKit` client with a
 * stubbed `fetch` that returns the corpus bytes verbatim — so the real transform runs on
 * the real payload.
 */

const corpusPath = fileURLToPath(
  new URL('./fixtures/comment-wire-corpus.json', import.meta.url)
);
const corpusText = readFileSync(corpusPath, 'utf8');
const corpus = JSON.parse(corpusText) as Array<Record<string, unknown>>;

/** The `Comment` interface's complete field set. Kept as a literal set so the assertion
 *  below is an equality, not a containment — a containment cannot see an extra field. */
const COMMENT_FIELDS = ['id', 'content', 'userId', 'isAdmin', 'createdAt'] as const;

const mockFetch = vi.fn();
global.fetch = mockFetch;

function respondWithCorpus(): void {
  mockFetch.mockResolvedValueOnce({
    ok: true,
    status: 200,
    headers: { get: () => 'application/json' },
    json: async () => JSON.parse(corpusText)
  });
}

describe('QA-UNIT04 -11 · JS comment decode', () => {
  beforeEach(() => {
    mockFetch.mockReset();
  });

  it('maps the server corpus onto the Comment interface with no missing and no extra field', async () => {
    respondWithCorpus();
    const client = new FeedbackKit({ apiKey: 'sf_test_key' });

    const comments: Comment[] = await client.comments.list(
      '33333333-3333-4333-8333-333333333333'
    );

    expect(comments).toHaveLength(2);
    for (const comment of comments) {
      // Set equality, both directions. `toHaveProperty` per field would be green over a
      // payload that also carried three keys the interface never declared.
      expect(Object.keys(comment).sort()).toEqual([...COMMENT_FIELDS].sort());
    }
  });

  it('carries every value through, including the admin flag and the ISO-8601 instant', async () => {
    respondWithCorpus();
    const client = new FeedbackKit({ apiKey: 'sf_test_key' });

    const comments = await client.comments.list('33333333-3333-4333-8333-333333333333');

    expect(comments[0]).toEqual({
      id: '11111111-1111-4111-8111-111111111111',
      content: 'Thanks for the report - this ships in 2.4.',
      userId: 'fixture-admin-user',
      isAdmin: true,
      createdAt: '2023-11-14T22:13:20Z'
    });
    expect(comments[1]).toEqual({
      id: '22222222-2222-4222-8222-222222222222',
      content: 'Please add dark mode.',
      userId: 'fixture-end-user',
      isAdmin: false,
      createdAt: '2023-11-14T23:13:20Z'
    });
  });

  it('leaves no residual snake_case key and no undefined value', async () => {
    respondWithCorpus();
    const client = new FeedbackKit({ apiKey: 'sf_test_key' });

    const comments = await client.comments.list('33333333-3333-4333-8333-333333333333');

    for (const comment of comments) {
      for (const [key, value] of Object.entries(comment)) {
        expect(key).not.toContain('_');
        expect(value).not.toBeUndefined();
      }
    }
    // Paired positive: array-element order is contractual and survived. The three
    // assertions above are all absences and would hold over an empty array.
    expect(comments.map((c) => c.userId)).toEqual([
      'fixture-admin-user',
      'fixture-end-user'
    ]);
  });

  it('the corpus fixture is the server shape and can express an admin-flag failure', () => {
    expect(corpus).toHaveLength(2);
    expect(Object.keys(corpus[0]).sort()).toEqual(
      ['content', 'created_at', 'id', 'is_admin', 'user_id'].sort()
    );
    // Load-bearing: one entry is admin-flagged and one is not, so a client that dropped
    // the flag could not satisfy the value assertions above.
    expect(corpus[0].is_admin).toBe(true);
    expect(corpus[1].is_admin).toBe(false);
  });
});
