import { describe, it, expect, vi, beforeEach } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { FeedbackKit } from '../src';
import { FeedbackStatus, FeedbackCategory } from '../src/models/types';
import type { Feedback } from '../src/models/types';

/**
 * `QA-UNIT05-FEEDBACK`, JS lane — `-04`, `-12`, and the record of two **absences**.
 *
 * The JS SDK declares `FeedbackStatus` and `FeedbackCategory` as bare TypeScript enums with
 * **no predicate and no display map at all**. There is no `canVote`, no `displayName`, no
 * tint. The can-vote rule exists in this ecosystem only as an inline expression inside the
 * React Native `VoteButton` component (finding **F1**), where nothing can call it.
 *
 * So this lane owns what it can: the wire spellings, both directions, and the decode of the
 * payload the server actually sends. The absences are asserted **as absences**, because
 * "the JS SDK has no predicate" is a claim in a document that nothing checks otherwise — and
 * the day one is added, `-09` and `-11` gain a client.
 *
 * The corpus in `tests/fixtures/feedback-wire-corpus.json` is **not** written here. It is
 * generated by the server's `FeedbackWireContractTests` from the server's own
 * `FeedbackResponseDTO` through the server's own configured encoder, and that suite
 * byte-diffs this committed copy against a fresh regeneration.
 *
 * The transform under test is `HttpClient`'s recursive `snakeToCamel`, which is
 * module-private. Rather than re-implement it — a second definition, and the exact thing this
 * suite exists to prevent — the cases drive the **real** `FeedbackKit` client with a stubbed
 * `fetch` returning the corpus bytes verbatim.
 */

const corpusPath = fileURLToPath(
  new URL('./fixtures/feedback-wire-corpus.json', import.meta.url)
);
const corpusText = readFileSync(corpusPath, 'utf8');
const corpus = JSON.parse(corpusText) as Array<Record<string, unknown>>;

/** The canon: root CLAUDE.md's six statuses and their wire spellings. */
const STATUS_WIRE: ReadonlyArray<readonly [FeedbackStatus, string]> = [
  [FeedbackStatus.Pending, 'pending'],
  [FeedbackStatus.Approved, 'approved'],
  [FeedbackStatus.InProgress, 'in_progress'],
  [FeedbackStatus.TestFlight, 'testflight'],
  [FeedbackStatus.Completed, 'completed'],
  [FeedbackStatus.Rejected, 'rejected']
];

const CATEGORY_WIRE: ReadonlyArray<readonly [FeedbackCategory, string]> = [
  [FeedbackCategory.FeatureRequest, 'feature_request'],
  [FeedbackCategory.BugReport, 'bug_report'],
  [FeedbackCategory.Improvement, 'improvement'],
  [FeedbackCategory.Other, 'other']
];

const mockFetch = vi.fn();
global.fetch = mockFetch;

function respondWithCorpus(): void {
  mockFetch.mockResolvedValueOnce({
    ok: true,
    status: 200,
    headers: { get: () => 'application/json' },
    json: async () => JSON.parse(corpusText)
  });
}

describe('QA-UNIT05 -04 · JS wire enum', () => {
  it('every status member carries its exact wire spelling', () => {
    for (const [member, spelling] of STATUS_WIRE) {
      expect(member).toBe(spelling);
    }
    // Cardinality, computed over the enum's own members rather than the table. A per-case
    // table cannot detect an ADDITION — a seventh case is simply not in it — and `testflight`
    // was itself added to this set after the first clients shipped.
    expect(Object.keys(FeedbackStatus)).toHaveLength(6);
    expect(new Set(Object.values(FeedbackStatus)).size).toBe(6);
  });

  it('every wire spelling resolves back to exactly one member', () => {
    const byValue = new Map(
      Object.entries(FeedbackStatus).map(([, value]) => [value as string, value as string])
    );
    for (const [, spelling] of STATUS_WIRE) {
      expect(byValue.get(spelling)).toBe(spelling);
    }
    // The negative, paired: an unknown token is not a member. TypeScript enums do no
    // validation at runtime, so this is a statement about the value set, not about parsing.
    expect(byValue.get('quantum')).toBeUndefined();
    expect(byValue.get('inProgress')).toBeUndefined();
  });

  it('every category member carries its exact wire spelling', () => {
    for (const [member, spelling] of CATEGORY_WIRE) {
      expect(member).toBe(spelling);
    }
    expect(Object.keys(FeedbackCategory)).toHaveLength(4);
    expect(new Set(Object.values(FeedbackCategory)).size).toBe(4);
  });
});

describe('QA-UNIT05 -09/-11 · the JS SDK declares no can-vote predicate (F1)', () => {
  it('neither enum exposes canVote or a display map', () => {
    // Recorded as an absence rather than left implicit. Five of the six shipped can-vote
    // declarations negate the terminal set; the JS SDK has none at all, and the RN component
    // reimplements it inline where nothing can call it. The day this reddens, extract the
    // predicate here and add the JS SDK to -09/-11's client list.
    expect((FeedbackStatus as Record<string, unknown>).canVote).toBeUndefined();
    expect((FeedbackStatus as Record<string, unknown>).displayName).toBeUndefined();
    expect((FeedbackCategory as Record<string, unknown>).canVote).toBeUndefined();

    // Paired positive: the enums really are the ones the census names, and they do carry
    // their six/four values — so this is not green over an undefined import.
    expect(FeedbackStatus.TestFlight).toBe('testflight');
    expect(FeedbackCategory.BugReport).toBe('bug_report');
  });
});

describe('QA-UNIT05 -12 · JS feedback decode', () => {
  beforeEach(() => {
    mockFetch.mockReset();
  });

  it('the corpus fixture is the server shape and can express a failure', () => {
    // Non-vacuity for the whole group. An emptied fixture, or one whose sparse entry had
    // quietly gained the optional keys, would leave every case below meaningless.
    expect(corpus).toHaveLength(3);
    expect(Object.keys(corpus[0])).toHaveLength(41);
    expect(corpus[0].sync_states).toBeDefined();
    expect(corpus[2].user_email).toBeUndefined();
    expect(corpus[2].sync_states).toBeUndefined();
  });

  it('maps every field the Feedback interface declares onto its camelCase name', async () => {
    respondWithCorpus();
    const client = new FeedbackKit({ apiKey: 'sf_test_key' });

    const items: Feedback[] = await client.feedback.list();

    expect(items).toHaveLength(3);
    const populated = items[0];

    expect(populated.id).toBe('11111111-1111-4111-8111-111111111111');
    expect(populated.title).toBe('Add a dark theme');
    expect(populated.description).toBe('The list is hard to read at night.');
    expect(populated.status).toBe(FeedbackStatus.InProgress);
    expect(populated.category).toBe(FeedbackCategory.FeatureRequest);
    expect(populated.userId).toBe('fixture-end-user');
    expect(populated.userEmail).toBe('fixture-user@example.invalid');
    expect(populated.voteCount).toBe(7);
    expect(populated.hasVoted).toBe(true);
    expect(populated.commentCount).toBe(3);
    expect(populated.totalMrr).toBe(250);
    expect(populated.createdAt).toBe('2023-11-14T22:13:20Z');
    expect(populated.updatedAt).toBe('2023-11-14T23:13:20Z');
    expect(populated.rejectionReason).toBe('Superseded by the theming epic.');
    expect(populated.mergedIntoId).toBe('44444444-4444-4444-8444-444444444444');
    expect(populated.mergedAt).toBe('2023-11-15T00:13:20Z');
    expect(populated.mergedFeedbackIds).toEqual([
      '55555555-5555-4555-8555-555555555555'
    ]);
    expect(populated.isHiddenOverLimit).toBe(true);
  });

  it('leaves no residual snake_case key, and the key set is the payload camelCased', async () => {
    respondWithCorpus();
    const client = new FeedbackKit({ apiKey: 'sf_test_key' });

    const items = await client.feedback.list();
    const populated = items[0] as unknown as Record<string, unknown>;

    // A TypeScript interface is erased at runtime, so the client does NOT strip the keys the
    // `Feedback` interface does not declare — the object carries all 41 camelCased. Asserted
    // as a set equality rather than a per-key presence: an oracle asserting a presence cannot
    // see an extra, and "and nothing else" is half of what -12 claims.
    const expectedKeys = Object.keys(corpus[0]).map((key) =>
      key.replace(/_([a-z0-9])/g, (_, char: string) => char.toUpperCase())
    );
    expect(Object.keys(populated).sort()).toEqual(expectedKeys.sort());

    for (const key of Object.keys(populated)) {
      expect(key).not.toContain('_');
    }
  });

  it('converts nested sync_states elements too, and keeps array order', async () => {
    respondWithCorpus();
    const client = new FeedbackKit({ apiKey: 'sf_test_key' });

    const items = await client.feedback.list();
    const syncStates = (items[0] as unknown as Record<string, unknown>)
      .syncStates as Array<Record<string, unknown>>;

    // `snakeToCamel` is recursive; nothing else in this repo asserts it reaches an array of
    // objects. Array-element order is contractual — object-key order is not.
    expect(syncStates).toHaveLength(2);
    expect(syncStates[0]).toEqual({
      provider: 'github',
      state: 'succeeded',
      providerRefUrl: 'https://github.example.invalid/acme/app/issues/41'
    });
    expect(syncStates[1]).toEqual({ provider: 'linear', state: 'pending' });
  });

  it('the sparse entry decodes with its optionals simply absent', async () => {
    respondWithCorpus();
    const client = new FeedbackKit({ apiKey: 'sf_test_key' });

    const sparse = (await client.feedback.list())[2];

    expect(sparse.userEmail).toBeUndefined();
    expect(sparse.totalMrr).toBeUndefined();
    expect(sparse.mergedIntoId).toBeUndefined();
    // Positive terminal signals rather than a green built from absences.
    expect(sparse.title).toBe('Crash on launch');
    expect(sparse.status).toBe(FeedbackStatus.Rejected);
    expect(sparse.category).toBe(FeedbackCategory.Other);
    expect(sparse.voteCount).toBe(0);
  });

  it('all three entries carry three distinct status and category tokens', async () => {
    respondWithCorpus();
    const client = new FeedbackKit({ apiKey: 'sf_test_key' });

    const items = await client.feedback.list();

    expect(items.map((i) => i.status)).toEqual([
      FeedbackStatus.InProgress,
      FeedbackStatus.TestFlight,
      FeedbackStatus.Rejected
    ]);
    expect(items.map((i) => i.category)).toEqual([
      FeedbackCategory.FeatureRequest,
      FeedbackCategory.BugReport,
      FeedbackCategory.Other
    ]);
  });
});
